In [14]:
import numpy as np
from scipy.optimize import linear_sum_assignment

# Define the input arrays
p_ijk = np.random.randint(1, 10, (5, 5, 4))  # Replace with actual processing times
h_ijk = np.random.randint(0, 2, (5, 5, 4))  # Replace with actual availability matrix
available_time_k = np.random.randint(0, 6, 4)  # Replace with actual machine availability times
ready_time = 3

# Print input arrays for debugging
print("p_ijk shape:", p_ijk.shape)
print("p_ijk:", p_ijk)
print("h_ijk shape:", h_ijk.shape)
print("h_ijk:", h_ijk)
print("available_time_k shape:", available_time_k.shape)
print("available_time_k:", available_time_k)

# ORSet to assign
ORSet = [(0, 1), (3, 4), (3, 2), (0, 0), (4, 3), (2, 1)]

# Initialize cost matrix with a high value (inf)
num_operations = len(ORSet)
num_machines = p_ijk.shape[2]
cost_matrix = np.full((num_operations, num_machines), 999)

# Print dimensions of cost matrix for debugging
print("cost_matrix shape:", cost_matrix.shape)

# Populate the cost matrix based on constraints
for op_idx, (i, j) in enumerate(ORSet):
    for k in range(num_machines):
        if h_ijk[i][j][k] == 1 and available_time_k[k] <= ready_time:
            cost_matrix[op_idx, k] = p_ijk[i][j][k]

# Print cost matrix for debugging
print("cost_matrix:", cost_matrix)

# Solve the assignment problem using the Hungarian algorithm
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Print indices for debugging
print("row indices:", row_ind)
print("column indices:", col_ind)

# Output the assignment results
assignments = [(ORSet[row], machine) for row, machine in zip(row_ind, col_ind) if cost_matrix[row, machine] < 999]
# Print the results
for (i, j), k in assignments:
    print(f"Assign operation ({i}, {j}) to machine {k} with cost {p_ijk[i][j][k]}")

assigned_operations = [ORSet[row] for row, machine in zip(row_ind, col_ind) if cost_matrix[row, machine] < 999]
unassigned_operations = [op for op in ORSet if op not in assigned_operations]

# Print unassigned ORSet
if unassigned_operations:
    print("Some ORSet could not be assigned to any machine under the given constraints:")
    print(unassigned_operations)
else:
    print("All ORSet have been successfully assigned.")


p_ijk shape: (5, 5, 4)
p_ijk: [[[8 3 4 4]
  [1 9 4 1]
  [6 6 4 5]
  [6 3 7 6]
  [9 1 9 1]]

 [[7 6 7 3]
  [8 8 2 6]
  [2 2 3 3]
  [3 2 5 7]
  [3 4 7 9]]

 [[4 2 5 7]
  [7 5 5 6]
  [3 9 7 6]
  [7 1 4 1]
  [9 3 3 3]]

 [[3 1 9 3]
  [4 3 2 6]
  [9 2 4 2]
  [8 2 4 8]
  [1 5 6 4]]

 [[4 7 1 1]
  [8 3 7 3]
  [4 5 4 2]
  [1 7 5 6]
  [6 3 3 4]]]
h_ijk shape: (5, 5, 4)
h_ijk: [[[1 0 1 1]
  [0 0 0 0]
  [0 0 1 0]
  [1 1 1 0]
  [1 0 0 1]]

 [[0 1 1 1]
  [1 1 0 1]
  [1 1 1 0]
  [0 0 0 0]
  [0 1 0 1]]

 [[0 1 1 1]
  [1 0 1 0]
  [1 0 1 0]
  [1 1 0 0]
  [0 1 1 0]]

 [[0 0 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [0 1 0 1]
  [1 1 1 1]]

 [[0 0 1 1]
  [0 1 0 0]
  [1 1 1 0]
  [1 1 1 0]
  [0 0 1 0]]]
available_time_k shape: (4,)
available_time_k: [3 4 4 1]
cost_matrix shape: (6, 4)
cost_matrix: [[999 999 999 999]
 [  1 999 999   4]
 [999 999 999   2]
 [  8 999 999   4]
 [  1 999 999 999]
 [  7 999 999 999]]
row indices: [0 1 2 3]
column indices: [1 0 3 2]
Assign operation (3, 4) to machine 0 with cost 1
Assign oper

In [15]:
import numpy as np
from scipy.optimize import linear_sum_assignment

# Define the input arrays
p_ijk = np.random.randint(1, 10, (5, 5, 4))  # Replace with actual processing times
h_ijk = np.random.randint(0, 2, (5, 5, 4))  # Replace with actual availability matrix
available_time_k = np.random.randint(0, 6, 4)  # Replace with actual machine availability times
ready_time = 3

# Operations to assign
ORSet = [(0, 1), (3, 4), (3, 2), (0, 0), (4, 3), (2, 1)]

# Initialize cost matrix with a high value (inf)
num_operations = len(ORSet)
num_machines = p_ijk.shape[2]  # Number of machines
cost_matrix = np.full((num_operations, num_machines), 999)

# Populate the cost matrix based on constraints
for op_idx, (i, j) in enumerate(ORSet):
    for k in range(num_machines):
        if h_ijk[i][j][k] == 1 and available_time_k[k] <= ready_time:
            cost_matrix[op_idx, k] = p_ijk[i][j][k]

# Solve the assignment problem using the Hungarian algorithm
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Output the assignment results
assignments = [(ORSet[row], machine) for row, machine in zip(row_ind, col_ind) if cost_matrix[row, machine] < 999]

# Print the results
for (i, j), k in assignments:
    print(f"Assign operation ({i}, {j}) to machine {k} with cost {p_ijk[i][j][k]}")

# Handle unassigned operations
assigned_operations = [ORSet[row] for row, machine in zip(row_ind, col_ind) if cost_matrix[row, machine] < 999]
unassigned_operations = [op for op in ORSet if op not in assigned_operations]

if unassigned_operations:
    print("Some operations could not be assigned to any machine under the given constraints:")
    print(unassigned_operations)
else:
    print("All operations have been successfully assigned.")


Assign operation (3, 2) to machine 2 with cost 1
Assign operation (0, 0) to machine 0 with cost 3
Assign operation (4, 3) to machine 3 with cost 5
Some operations could not be assigned to any machine under the given constraints:
[(0, 1), (3, 4), (2, 1)]


In [16]:
import numpy as np
estimated_tardiness = np.full(4, -np.inf)

print(estimated_tardiness)

estimated_tardiness[0] = 2
print(estimated_tardiness)

print(np.argmax(estimated_tardiness))

[-inf -inf -inf -inf]
[  2. -inf -inf -inf]
0
