In [52]:
import pandas as pd
import numpy as np

# Load the Excel file
df = pd.read_excel(r"D:\D\University\4th year\Thesis\Code T5\data.xlsx")

# Defining total number of jobs (J) and total number of machines (K)
J = 20
K = 8

# Ensure MachineID is treated as a string
df['MachineID'] = df['MachineID'].astype(str)

# Get the unique ComponentIDs
unique_components = df['ComponentID'].unique()

# Create a list to hold all selected components
all_components = list(unique_components)

# Randomly add additional components to make the total number of jobs equal to J
if len(all_components) < J:
    additional_components = np.random.choice(unique_components, J - len(all_components), replace=True)
    all_components.extend(additional_components)

# Count the number of operations per component
operation_count = df['ComponentID'].value_counts().to_dict()

# Ensure all selected components are present in the operation_count
for comp in all_components:
    if comp not in operation_count:
        operation_count[comp] = 0

# Defining a deadline for each component (random or fixed for simplicity)
deadlines = {i: 150 for i in range(J)}

# Creating the text file in the specified format
output_file = 'jobs.txt'

with open(output_file, 'w') as f:
    f.write(f"{J}\n")
    f.write(f"{K}\n")
    f.write(" ".join(str(operation_count[comp_id]) for comp_id in sorted(operation_count.keys())) + "\n")
    f.write(" ".join(str(deadlines[comp_id]) for comp_id in range(J)) + "\n")
    job_id = 1
    for comp_id in all_components:
        comp_df = df[df['ComponentID'] == comp_id]
        for op_id, row in enumerate(comp_df.itertuples(), start=1):
            machines = row.MachineID.replace(' ', '').split(',')
            for machine in machines:
                f.write(f"{job_id} {op_id} {machine} {row.Duration}\n")
        job_id += 1

print(f"Text file '{output_file}' has been created.")


Text file 'jobs.txt' has been created.


In [19]:
import numpy as np

A = np.random.randint(2, 10, size = (3, 2, 5)) 
print(A)



B = np.mean(A, axis = 2)
print(B)

C = np.sum(B)
print(C)


[[[4 9 2 4 6]
  [6 8 3 2 5]]

 [[3 8 8 3 5]
  [9 2 8 3 8]]

 [[6 5 2 9 4]
  [4 8 3 6 4]]]
[[5.  4.8]
 [5.4 6. ]
 [5.2 5. ]]
31.400000000000002


In [22]:
import numpy as np

p_ijk = np.random.randint(0, 15, size  = (5, 4, 2))
h_ijk = np.random.randint(0, 2, size= (5, 4, 2))
d_j = np.array([10, 12, 10, 11, 10])
T_cur = 2
JSet = [0, 1, 2, 3, 4]
J = 10
Tard_job = [1, 2]

p_mean = np.mean(p_ijk*h_ijk, axis=2)
p_mean_left = np.zeros(J)
p_mean_left[JSet] = np.sum(p_mean[OP[JSet]:, JSet])


# Get n_j (which should be the size of the first dimension of p_ijk)
n_j = np.array([4, 4, 4, 5, 4])
n_ops_left_j = np.array([1, 1, 2, 2, 4])

OP = n_j - n_ops_left_j
estimated_tardiness = np.full(J, np.inf)
for j in Tard_job:
    estimated_tardiness[j] = T_cur + np.sum(p_mean[OP[j]:n_j[j], j] - d_j[j])

j = np.argmin(estimated_tardiness)

print(estimated_tardiness)
print(j)


TypeError: only integer scalar arrays can be converted to a scalar index

In [3]:
import numpy as np

A = np.random.randint(0, 10, size= (5, 10))
print(A)
B = A[2:]
                       
print(B)

[[5 0 9 3 0 6 6 2 7 8]
 [4 3 4 2 7 0 9 7 8 2]
 [4 1 0 1 1 4 6 0 6 7]
 [0 7 0 2 0 3 6 3 1 0]
 [6 3 8 7 9 6 6 7 3 0]]
[[4 1 0 1 1 4 6 0 6 7]
 [0 7 0 2 0 3 6 3 1 0]
 [6 3 8 7 9 6 6 7 3 0]]
